# docker-compose.yml (minimal)
version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: hanna_db
      POSTGRES_USER: hanna_user
      POSTGRES_PASSWORD: hanna_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: