spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:hanna_db}
    username: ${DB_USERNAME:hanna_user}
    password: ${DB_PASSWORD:hanna_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

  config:
    import: optional:file:.env[.properties]

server:
  port: 8081

# Custom Application Properties - Test Environment
app:
  name: "Hanna Test"
  version: "1.0.0-test"
  
  security:
    jwtSecret: ${JWT_SECRET}
    jwtExpirationMs: 1800000  # 30 minutes for test
    corsAllowedMethods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"
  
  allowedOrigins:
    - "http://localhost:3000"
    - "http://localhost:8081"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  show-actuator: true