spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:hanna_db}
    username: ${DB_USERNAME:hanna_user}
    password: ${DB_PASSWORD:hanna_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  config:
    import: optional:file:.env[.properties]

server:
  port: 8080

debug: false

# Custom Application Properties - Production Environment
app:
  name: "Hanna Production"
  version: "1.0.0"
  
  security:
    jwtSecret: ${JWT_SECRET}
    jwtExpirationMs: 86400000  # 24 hours for prod
    corsAllowedMethods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
  
  allowedOrigins:
    - "https://example.com"
    - "https://www.example.com"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: false  # Disabled in production for security
  show-actuator: false