spring:
  application:
    name: hanna

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
    import: optional:file:.env[.properties]

server:
  port: 8080

# Custom Application Properties
app:
  name: "Hanna Application"
  version: "1.0.0"
  
  security:
    jwtSecret: ${JWT_SECRET}
    jwtExpirationMs: 86400000
    corsAllowedMethods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"
  
  allowedOrigins:
    - "http://localhost:3000"
    - "http://localhost:8080"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  show-actuator: true