spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:hanna_db}
    username: ${DB_USERNAME:hanna_user}
    password: ${DB_PASSWORD:hanna_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  config:
    import: optional:file:.env[.properties]

server:
  port: 8080

debug: true

# Custom Application Properties - Development Environment
app:
  name: "Hanna Development"
  version: "1.0.0-dev"
  
  security:
    jwtSecret: ${JWT_SECRET}
    jwtExpirationMs: 3600000  # 1 hour for dev
    corsAllowedMethods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"
  
  allowedOrigins:
    - "http://localhost:3000"
    - "http://localhost:8080"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  show-actuator: true